[build]
  command = "npx --yes @genkit-ai/tools@latest genkit-next-plugin-pre-build && next build"
  publish = ".next"

[build.environment]
  GENKIT_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"
